### ISSUE TITLE
Add scrollbars?

### ISSUE THREAD

**Issue by jomiplaz** [MayLau-CbL/flutter_horizontal_data_table#13]
Hi, it is possible to add a horizontal and vertical scrollbar? I think that with scrollbar widget might work.

Thanks.

**Comment by MayLau-CbL** [comment]
Hello @jomiplaz, I have added the scrollbar widget to the package. It seems okay on my android testing device and the browser. Since I have no IOS device currently on hand and previously I have faced an issue about the scrollbar widget and SafeArea together on the IOS platform. I published a  pre-release build on the pub.dev for testing. :-)
You may check it:
A new class ScrollbarStyle is added and updated on the README.md. You may take a look.
https://pub.dev/packages/horizontal_data_table/versions/1.0.7-dev

**Comment by SSebigo** [comment]
@MayLau-CbL Is this issue gonna make it to stable? It has been in dev for 5 months so I'm wondering.

**Comment by MayLau-CbL** [comment]
Thank you for asking, @SSebigo 
Yes, it is planning to have stable release after the UI enhancement branch merged ([ui-performance-opt](https://github.com/MayLau-CbL/flutter_horizontal_data_table/tree/update/ui-performance-opt)). Approximately, should be around the end of March or early April. 

This is reason I dunt want to stable the v1.0.7 as that one's handling will make the vertical scrollbar not able to reach the end of the widget when the scroll is already reach its end. A little bit like floating on the bottom. The new Ui enhancement although still have some issues on it, but at least it is having a better look than that.
