### ISSUE TITLE
No Shadow effect when scrolling horizontally

### ISSUE THREAD

**Issue by Errechydy** [MayLau-CbL/flutter_horizontal_data_table#3]
Thanks for this great package.
I noticed in the video that when you school horizontally a shadow appears at the right side of the first column, but when it doesn't appear when using the code example you provided. Can you please add that shadow.

**Comment by MayLau-CbL** [comment]
Thank you for reporting this issue!

I find that this is related to the Material widget elevation effect having different behavior to previous version with the Row widget. I now updated a new version v1.0.5 which uses the box shadow instead of the Material widget.

Also, I have added a new field elevationColor which allows to use different color shadow instead of the default black one which may benefit to user who want to use a dark table background. 

If still have any issue based on the shadow, please re-open this. Thank you!

**Comment by Errechydy** [comment]
Thanks for the update, noticed that the the shadow cross the table header which doesn't look good. it will be great if it doesn't cross it

**Comment by R4x03** [comment]
Hi! 
I think I have the same problem.
When I scroll horizontally, I don't have any shadow and the screen doesn't lock the table to the edge of the screen (the table spills out of the screen)

<img width="208" alt="Capture d’écran 2021-11-23 à 12 19 45" src="https://user-images.githubusercontent.com/64418839/143015603-b0252b22-dc59-41ac-b4ba-52e02d4cccf5.png">

Here, the white under the green header should not be there
