### ISSUE TITLE
Any reason why this is not being implement in the existing DataTable widget?

### ISSUE THREAD

**Issue by Bonsai11** [MayLau-CbL/flutter_horizontal_data_table#55]
Wouldn't it be better to improve the existing DataTable widget instead of creating a new widget that does the same thing but adds a few features?

**Comment by MayLau-CbL** [comment]
For your question, i think you can checkout this https://github.com/flutter/flutter/issues/21165 and https://material.io/components/data-tables#usage. For why i am not improving the existing one directly because i have no idea where i can  start customizing it with both fixed column and lazy loading in DataTable widget. I don't feel flutter team will implement this to the DataTable in short time as you can see the design concept they are introducing.  Therefore, if you have an idea to implement it on DataTable, please kindly go ahead help contribute it. This will help many developers.

**Comment by MayLau-CbL** [comment]
If no further questions, i close this issue for now
