### ISSUE TITLE
[Question] Any way to change the background color?

### ISSUE THREAD

**Issue by SwiftCODA** [MayLau-CbL/flutter_horizontal_data_table#91]
**Describe the Problem**
Can't change the background color of the vertical scrolling.

Using the default bouncing physics, a white background appears when you scroll too far up or down. Is there any way to change this to a different color? I have a dark UI and the white looks awful when you scroll past, yet I would like to keep the bouncing physics.

**Comment by MayLau-CbL** [comment]
Have you try to set the leftHandSideColBackgroundColor and rightHandSideColBackgroundColor? Default they are white in color.

**Comment by SwiftCODA** [comment]
> 

Hey, I misunderstood the meaning of that attribute. That is what I wanted. Although there is something I think the background color system is missing. 

In my case, I have set up alternating row colors. When using bouncing physics horizontally, I would like to be able to have the background still show the alternating colors rather than just a solid color. Do you know what I mean?

**Comment by MayLau-CbL** [comment]
i see, your case is a bit complicated since you need to either (1) calculate the list children position and height or (2) use LinkedConrtoller registering every row with 1 controller to control the horizontal movement instead of the existing way in this package.

If you every row is sharing the same height, it might be possible to fork this package and apply the calulated background color to replace the Container's color.

If it is not all the same, I suggest you use the (2) approches. You may fork or create a new widget since the implementation on the scroll approch will be having big difference. Since you have to register a scroll controller to every row, I doubt the performance of the resultant widget be. Currently, this package's body is using one scrollcontroller for its horizontal scrolling to avoid many scroll controller being created and disposed while user swipe up and down to prevent lag on lower spec phone as possible. 

Hope these information can help you.😃

**Comment by MayLau-CbL** [comment]
no further comment, close this first
